<?php
namespace app\index\model;
use think\Model;
class Admin extends Model{
    private $filed=true;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}